### PR TITLE
Feature/embed hiredis

### PR DESCRIPTION
**Pull request by eddelbuettel**
@armstrtw If you have a moment at work on Monday, look this over -- should be fine

I finally gave up on CRAN's ability to eventually procure a `libhiredis` where it hadn't yet -- ie macOS -- so I stuck in here as a fallback.  On normal systems we still use an external hiredis.

Also made RcppMsgPack unconditional at the C++ side as the package already pulled it in.

### CODE REVIEW

**Comment by armstrtw** [comment]
I'll check it out.  Also if you feel like waiting another day or so, I plan to add a few more of the commands for hashes.  Sometimes cran seems a bit finicky about accepting multiple releases in a short period.

**Comment by eddelbuettel** [comment]
Sure, just give me a heads-up as you just did, and as we (ahem, ahem, ...) suggest in some [Contributing.md](https://github.com/RcppCore/Rcpp/blob/master/Contributing.md)  (different repo, same idea):  _issue ticket first_ is always a good plan so that everybody is on the same page.  

Also, if I may, before you branch next let me merge this so that we have clean history graphs.

**Comment by eddelbuettel** [comment]
@armstrtw Did you get a chance to look at it yet?

**Comment by armstrtw** [comment]
Sorry for the delay.  This compiles/installs and produces expected results for my local scripts.  Was there anything in particular that you wanted me to test?

**Pull request merged**
